### ISSUE TITLE
fatal error: cublas_v2.h: No such file or directory

### ISSUE THREAD

**Issue by ghasemikasra39** [facebookresearch/NSVF#27]
**Describe the bug**
I am trying to run your project. When running `pip install --editable ./` or `python setup.py build_ext --inplace` I am getting the following output:

```
Obtaining file:///tmp/kghasemi/NSVF
Installing collected packages: fairnr
  Running setup.py develop for fairnr
    ERROR: Command errored out with exit status 1:
     command: /tmp/kghasemi/conda/envs/nsvf-env/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/kghasemi/NSVF/setup.py'"'"'; __file__='"'"'/tmp/kghasemi/NSVF/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps
         cwd: /tmp/kghasemi/NSVF/
    Complete output (23 lines):
    running develop
    running egg_info
    writing fairnr.egg-info/PKG-INFO
    writing dependency_links to fairnr.egg-info/dependency_links.txt
    writing entry points to fairnr.egg-info/entry_points.txt
    writing top-level names to fairnr.egg-info/top_level.txt
    reading manifest file 'fairnr.egg-info/SOURCES.txt'
    writing manifest file 'fairnr.egg-info/SOURCES.txt'
    running build_ext
    building 'fairnr.clib._ext' extension
    creating build/temp.linux-x86_64-3.7
    creating build/temp.linux-x86_64-3.7/fairnr
    creating build/temp.linux-x86_64-3.7/fairnr/clib
    creating build/temp.linux-x86_64-3.7/fairnr/clib/src
    gcc -pthread -B /tmp/kghasemi/conda/envs/nsvf-env/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/tmp/kghasemi/conda/envs/nsvf-env/lib/python3.7/site-packages/torch/include -I/tmp/kghasemi/conda/envs/nsvf-env/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/tmp/kghasemi/conda/envs/nsvf-env/lib/python3.7/site-packages/torch/include/TH -I/tmp/kghasemi/conda/envs/nsvf-env/lib/python3.7/site-packages/torch/include/THC -I/usr/local/cuda-10.1/include -I/tmp/kghasemi/conda/envs/nsvf-env/include/python3.7m -c fairnr/clib/src/octree.cpp -o build/temp.linux-x86_64-3.7/fairnr/clib/src/octree.o -O2 -Ifairnr/clib/include -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_ext -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
    In file included from fairnr/clib/src/../include/utils.h:7:0,
                     from fairnr/clib/src/octree.cpp:7:
    /tmp/kghasemi/conda/envs/nsvf-env/lib/python3.7/site-packages/torch/include/ATen/cuda/CUDAContext.h:7:10: fatal error: cublas_v2.h: No such file or directory
     #include <cublas_v2.h>
              ^~~~~~~~~~~~~
    compilation terminated.
    error: command 'gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /tmp/kghasemi/conda/envs/nsvf-env/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/kghasemi/NSVF/setup.py'"'"'; __file__='"'"'/tmp/kghasemi/NSVF/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command output.
```

**To Reproduce**
1. `git clone https://github.com/facebookresearch/NSVF.git`
2. `cd NSVF`
3. `conda install pytorch==1.4.0 torchvision==0.5.0 cudatoolkit=10.1 -c pytorch` 
4. `pip install -r requirements.txt`
5. `pip install --editable ./`

If you don't execute step 3, you will get this error:
```
    ERROR: Command errored out with exit status 1:
     command: /tmp/kghasemi/conda/envs/nsvf-env/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-09c9r6sr/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-09c9r6sr/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-cn8dm7pt
         cwd: /tmp/pip-req-build-09c9r6sr/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-09c9r6sr/setup.py", line 2, in <module>
        from torch.utils.cpp_extension import BuildExtension, CUDA_HOME
    ModuleNotFoundError: No module named 'torch'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Expected behavior**
When I execute `find /usr/local/ -name cublas_v2.h`, I get this `/usr/local/cuda-10.2/targets/x86_64-linux/include/cublas_v2.h`
which means the header exist. 
Therefore I should not get this error. 

**Screenshots**
![Screenshot 2020-11-14 at 19 06 47](https://user-images.githubusercontent.com/24314029/99153982-928ee200-26ac-11eb-93eb-41f8adbe7245.png)

**Desktop (please complete the following information):**
```
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.1 LTS
Release:        18.04
Codename:       bionic
```

**Env**
```
cudatoolkit               10.1.243             h6bb024c_0  
pytorch                   1.4.0           py3.7_cuda10.1.243_cudnn7.6.3_0    pytorch
lpips-pytorch             latest                   pypi_0    pypi
pytorch                   1.4.0           py3.7_cuda10.1.243_cudnn7.6.3_0    pytorch
torchvision               0.5.0                py37_cu101    pytorch
ipython                   7.19.0                   pypi_0    pypi
ipython-genutils          0.2.0                    pypi_0    pypi
opencv-python             4.2.0.32                 pypi_0    pypi
python                    3.7.9                h7579374_0  
python-dateutil           2.8.1                    pypi_0    pypi
```

**Comment by MultiPath** [comment]
Hi I noticed you mentioned:

"When I execute find /usr/local/ -name cublas_v2.h, I get this /usr/local/cuda-10.2/targets/x86_64-linux/include/cublas_v2.h
which means the header exist.
Therefore I should not get this error."

It appears ``cuda-10.2`` which does not match with pytorch (cuda 10.1) and the requirements of our code?

**Comment by ghasemikasra39** [comment]
dear @MultiPath 
I can confirm that the issue above was due to our own misconfiguration. It's working fine now. I will close this issue.

**Comment by caj12306** [comment]
I met the same problem as you, how did you solve it at last? @ghasemikasra39
