### ISSUE TITLE
KeyError: 'step' in write_images(self.writer, images, self._num_updates['step'])

### ISSUE THREAD

**Issue by ghasemikasra39** [facebookresearch/NSVF#31]
**Describe the bug**
I have tried your example script for **evaluation**:
```Bash
DATA="Wineholder"
RES="800x800"
ARCH="nsvf_base"
SUFFIX="v1"
DATASET=/private/home/jgu/data/shapenet/release/Synthetic_NSVF/${DATA}
SAVE=/checkpoint/jgu/space/neuralrendering/new_release/$DATA
MODEL=$ARCH$SUFFIX
MODEL_PATH=$SAVE/$MODEL/checkpoint_last.pt

# start validating a trained model with target images.
# CUDA_VISIBLE_DEVICES=0 \
python validate.py ${DATASET} \
    --user-dir fairnr \
    --valid-views "200..400" \
    --valid-view-resolution "800x800" \
    --no-preload \
    --task single_object_rendering \
    --max-sentences 1 \
    --valid-view-per-batch 1 \
    --path ${MODEL_PATH} \
    --model-overrides '{"chunk_size":1024,"raymarching_tolerance":0.01,"tensorboard_logdir":"","eval_lpips":True}' \
```

Using this script I could do an evaluation using my trained model. However, the reconstructed images are missing in `tensorboard`. I noticed that you are passing `tensorboard_logdir` as an empty string in `--model-overrides` option. I tried  populating it. I also added `--results-path` option. Here you can find my script :
```Bash
MODEL="nsvf_basev1"
MODEL_PATH=checkpoint/${DATA}/${MODEL}/checkpoint_best.pt
SAVE=eval/${DATA}/${MODEL}
NAME="${DATA}_${MODEL}"
TB_LOG=checkpoint/${DATA}/tensorboard/${MODEL}


python validate.py ${DATASET} \
    --user-dir fairnr \
    --valid-views "200..205" \
    --valid-view-resolution "800x800" \
    --no-preload \
    --task single_object_rendering \
    --max-sentences 1 \
    --valid-view-per-batch 1 \
    --path ${MODEL_PATH} \
    --model-overrides "{'chunk_size' : 512,'raymarching_tolerance' : 0.01, 'tensorboard_logdir' : '${TB_LOG}', 'eval_lpips' : True}" \
    --results-path ${SAVE} \
```

However, when running the script, I get this error:
```Bash
  | valid on 'valid' subset:   0%|                 | 0/200 [00:00<?, ?it/s]Building EasyOctree done. total #nodes = 11371, terminal #nodes = 5026 (time taken 1.524386 s)
Traceback (most recent call last):
   File "validate.py", line 11, in <module>
     cli_main()
   File "/tmp/kghasemi/NSVF/fairnr_cli/validate.py", line 153, in cli_main
     distributed_utils.call_main(args, main, override_args=override_args)
   File "/tmp/kghasemi/conda/lib/python3.8/site-packages/fairseq/distributed_utils.py", line 189, in call_main
     main(args, **kwargs)
   File "/tmp/kghasemi/NSVF/fairnr_cli/validate.py", line 114, in main
     _loss, _sample_size, log_output = task.valid_step(sample, model, criterion)
   File "/tmp/kghasemi/NSVF/fairnr/tasks/neural_rendering.py", line 308, in valid_step
     write_images(self.writer, images, self._num_updates['step'])
KeyError: 'step'
```

I search this part of the code but could not figure out what the issue was:
```Python
    def valid_step(self, sample, model, criterion):
        loss, sample_size, logging_output = super().valid_step(sample, model, criterion)
        model.add_eval_scores(logging_output, sample, model.cache, criterion, outdir=self.output_valid)
        if self.writer is not None:
            images = model.visualize(sample, shape=0, view=0)
            if images is not None:
                write_images(self.writer, images, self._num_updates['step'])
```

**To Reproduce**
1. Train a model on an arbitrary dataset
2. Using your trained model. try to do an evaluation

**Expected behavior**
The evaluation should not produce any error and reconstructed images must appear in the Tensorboard

**Screenshots**
![Screenshot 2020-11-29 at 16 25 44](https://user-images.githubusercontent.com/24314029/100546078-9e0f0b00-325f-11eb-8aa9-10aa789e834a.png)

**Desktop (please complete the following information):**
```
Ubuntu 18.04.1 LTS (GNU/Linux 4.15.0-123-generic x86_64)
```

**Comment by benjamin3344** [comment]
Same problem. In fact, I didn't get the output for the evaluation.
