### ISSUE TITLE
insufficient shared memory (i think) during render

### ISSUE THREAD

**Issue by scott-vsi** [facebookresearch/NSVF#40]
**Describe the bug**
I get an exception when trying to run render.py on the synthetic wine-holder example.

**To Reproduce**
Run the wine-holder example using the command in the README:

```
DATASET=/opt/Synthetic_NSVF/Wineholder
SAVE=/opt/output
python -u train.py ${DATASET} \
    --user-dir fairnr \
    --task single_object_rendering \
    --train-views "0..100" --view-resolution "800x800" \
    --max-sentences 1 --view-per-batch 4 --pixel-per-view 2048 \
    --no-preload \
    --sampling-on-mask 1.0 --no-sampling-at-reader \
    --valid-views "100..200" --valid-view-resolution "400x400" \
    --valid-view-per-batch 1 \
    --transparent-background "1.0,1.0,1.0" --background-stop-gradient \
    --arch nsvf_base \
    --initial-boundingbox ${DATASET}/bbox.txt \
    --use-octree \
    --raymarching-stepsize-ratio 0.125 \
    --discrete-regularization \
    --color-weight 128.0 --alpha-weight 1.0 \
    --optimizer "adam" --adam-betas "(0.9, 0.999)" \
    --lr 0.001 --lr-scheduler "polynomial_decay" --total-num-update 150000 \
    --criterion "srn_loss" --clip-norm 0.0 \
    --num-workers 0 \
    --seed 2 \
    --save-interval-updates 500 --max-update 150000 \
    --virtual-epoch-steps 5000 --save-interval 1 \
    --half-voxel-size-at  "5000,25000,75000" \
    --reduce-step-size-at "5000,25000,75000" \
    --pruning-every-steps 2500 \
    --keep-interval-updates 5 --keep-last-epochs 5 \
    --log-format simple --log-interval 1 \
    --save-dir ${SAVE} \
    --tensorboard-logdir ${SAVE}/tensorboard \
    | tee -a $SAVE/train.log
```

I was able to run for 15 checkpoints before it hung due to memory errors. I am able to export a ply with extract.py and it looks good.

Try to render from given camera poses with the command in the README:

```
MODEL_PATH=${SAVE}/checkpoint_best.pt
python render.py ${DATASET} \
    --user-dir fairnr \
    --task single_object_rendering \
    --path ${MODEL_PATH} \
    --model-overrides '{"chunk_size":512,"raymarching_tolerance":0.01}' \
    --render-save-fps 24 \
    --render-resolution "800x800" \
    --render-camera-poses ${DATASET}/pose \
    --render-views "200..400" \
    --render-output ${SAVE}/output \
    --render-output-types "color" "depth" "voxel" "normal" --render-combine-output \
    --log-format "simple"
```
 
Results in this exception:

```
2021-01-08 21:46:18 | INFO | fairnr.renderer | rendering starts. fairnr BaseModel
ERROR: Unexpected bus error encountered in worker. This might be caused by insufficient shared memory (shm).
Building EasyOctree done. total #nodes = 10097, terminal #nodes = 4457 (time taken 2.363832 s)
Building EasyOctree done. total #nodes = 10097, terminal #nodes = 4457 (time taken 2.387693 s)
Building EasyOctree done. total #nodes = 10097, terminal #nodes = 4457 (time taken 2.516335 s)
Traceback (most recent call last):
  File "render.py", line 11, in <module>
    cli_main()
  File "/src/NSVF/fairnr_cli/render_multigpu.py", line 137, in cli_main
    distributed_utils.call_main(args, main)
  File "/venv/lib/python3.7/site-packages/fairseq/distributed_utils.py", line 174, in call_main
    args.distributed_world_size,
  File "/venv/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 171, in spawn
    while not spawn_context.join():
  File "/venv/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 118, in join
    raise Exception(msg)
Exception: 

-- Process 1 terminated with the following error:
Traceback (most recent call last):
  File "/venv/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 761, in _try_get_data
    data = self._data_queue.get(timeout=timeout)
  File "/usr/lib/python3.7/multiprocessing/queues.py", line 105, in get
    raise Empty
_queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/venv/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 19, in _wrap
    fn(i, *args)
  File "/venv/lib/python3.7/site-packages/fairseq/distributed_utils.py", line 156, in distributed_main
    main(args, **kwargs)
  File "/src/NSVF/fairnr_cli/render_multigpu.py", line 35, in main
    return _main(args, sys.stdout)
  File "/src/NSVF/fairnr_cli/render_multigpu.py", line 108, in _main
    for i, sample in enumerate(t):
  File "/venv/lib/python3.7/site-packages/fairseq/logging/progress_bar.py", line 245, in __iter__
    for i, obj in enumerate(self.iterable, start=self.n):
  File "/venv/lib/python3.7/site-packages/fairseq/data/iterators.py", line 61, in __iter__
    for x in self.iterable:
  File "/venv/lib/python3.7/site-packages/fairseq/data/iterators.py", line 517, in __next__
    raise item
  File "/venv/lib/python3.7/site-packages/fairseq/data/iterators.py", line 454, in run
    item = next(self._source_iter)
  File "/venv/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 345, in __next__
    data = self._next_data()
  File "/venv/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 841, in _next_data
    idx, data = self._get_data()
  File "/venv/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 808, in _get_data
    success, data = self._try_get_data()
  File "/venv/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 774, in _try_get_data
    raise RuntimeError('DataLoader worker (pid(s) {}) exited unexpectedly'.format(pids_str))
RuntimeError: DataLoader worker (pid(s) 152108) exited unexpectedly
```

I tried running with the other checkpoints but got the same thing. Is there a parameter I can tweak to avoid these memory issues?

**Desktop (please complete the following information):**
 - Ubuntu 18.04
 - CUDA 10.1
 - 4 NVidia Tesla V100 w/ 32GB RAM

**Comment by scott-vsi** [comment]
I am still not sure as to the cause of this crash, but it seems it can be avoided by setting `--num-workers=0`, which means run on the main process.
