### ISSUE TITLE
Build is not working

### ISSUE THREAD

**Issue by nvibd** [facebookresearch/NSVF#50]
**Describe the bug**
There are build failures:
```
$ pip install --editable ./
Obtaining file:///home/user/dev/NSVF
Installing collected packages: fairnr
  Running setup.py develop for fairnr
    ERROR: Command errored out with exit status 1:
     command: /home/user/miniconda3/envs/python37/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/user/dev/NSVF/setup.py'"'"'; __file__='"'"'/home/user/dev/NSVF/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps
         cwd: /home/user/dev/NSVF/
    Complete output (120 lines):
    running develop
    running egg_info
    writing fairnr.egg-info/PKG-INFO
    writing dependency_links to fairnr.egg-info/dependency_links.txt
    writing entry points to fairnr.egg-info/entry_points.txt
    writing top-level names to fairnr.egg-info/top_level.txt
    reading manifest file 'fairnr.egg-info/SOURCES.txt'
    writing manifest file 'fairnr.egg-info/SOURCES.txt'
    running build_ext
    building 'fairnr.clib._ext' extension
    Emitting ninja build file /home/user/dev/NSVF/build/temp.linux-x86_64-3.7/build.ninja...
    Compiling objects...
    Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
    /home/user/miniconda3/envs/python37/lib/python3.7/site-packages/torch/cuda/__init__.py:104: UserWarning:
    NVIDIA GeForce RTX 3090 with CUDA capability sm_86 is not compatible with the current PyTorch installation.
    The current PyTorch install supports CUDA capabilities sm_37 sm_50 sm_60 sm_70.
    If you want to use the NVIDIA GeForce RTX 3090 GPU with PyTorch, please check the instructions at https://pytorch.org/get-started/locally/
    
      warnings.warn(incompatible_device_warn.format(device_name, capability, " ".join(arch_list), device_name))
    [1/6] c++ -MMD -MF /home/user/dev/NSVF/build/temp.linux-x86_64-3.7/fairnr/clib/src/intersect.o.d -pthread -B /home/user/miniconda3/envs/python37/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/user/miniconda3/envs/python37/lib/python3.7/site-packages/torch/include -I/home/user/miniconda3/envs/python37/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/home/user/miniconda3/envs/python37/lib/python3.7/site-packages/torch/include/TH -I/home/user/miniconda3/envs/python37/lib/python3.7/site-packages/torch/include/THC -I/usr/local/cuda-11.0/include -I/home/user/miniconda3/envs/python37/include/python3.7m -c -c /home/user/dev/NSVF/fairnr/clib/src/intersect.cpp -o /home/user/dev/NSVF/build/temp.linux-x86_64-3.7/fairnr/clib/src/intersect.o -O2 -Ifairnr/clib/include -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=_ext -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
    FAILED: /home/user/dev/NSVF/build/temp.linux-x86_64-3.7/fairnr/clib/src/intersect.o
    c++ -MMD -MF /home/user/dev/NSVF/build/temp.linux-x86_64-3.7/fairnr/clib/src/intersect.o.d -pthread -B /home/user/miniconda3/envs/python37/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/user/miniconda3/envs/python37/lib/python3.7/site-packages/torch/include -I/home/user/miniconda3/envs/python37/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/home/user/miniconda3/envs/python37/lib/python3.7/site-packages/torch/include/TH -I/home/user/miniconda3/envs/python37/lib/python3.7/site-packages/torch/include/THC -I/usr/local/cuda-11.0/include -I/home/user/miniconda3/envs/python37/include/python3.7m -c -c /home/user/dev/NSVF/fairnr/clib/src/intersect.cpp -o /home/user/dev/NSVF/build/temp.linux-x86_64-3.7/fairnr/clib/src/intersect.o -O2 -Ifairnr/clib/include -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=_ext -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
    /home/user/dev/NSVF/fairnr/clib/src/intersect.cpp:6:10: fatal error: intersect.h: No such file or directory
        6 | #include "intersect.h"
          |          ^~~~~~~~~~~~~
    compilation terminated.
    [2/6] c++ -MMD -MF /home/user/dev/NSVF/build/temp.linux-x86_64-3.7/fairnr/clib/src/octree.o.d -pthread -B /home/user/miniconda3/envs/python37/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/user/miniconda3/envs/python37/lib/python3.7/site-packages/torch/include -I/home/user/miniconda3/envs/python37/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/home/user/miniconda3/envs/python37/lib/python3.7/site-packages/torch/include/TH -I/home/user/miniconda3/envs/python37/lib/python3.7/site-packages/torch/include/THC -I/usr/local/cuda-11.0/include -I/home/user/miniconda3/envs/python37/include/python3.7m -c -c /home/user/dev/NSVF/fairnr/clib/src/octree.cpp -o /home/user/dev/NSVF/build/temp.linux-x86_64-3.7/fairnr/clib/src/octree.o -O2 -Ifairnr/clib/include -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=_ext -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
    FAILED: /home/user/dev/NSVF/build/temp.linux-x86_64-3.7/fairnr/clib/src/octree.o
    c++ -MMD -MF /home/user/dev/NSVF/build/temp.linux-x86_64-3.7/fairnr/clib/src/octree.o.d -pthread -B /home/user/miniconda3/envs/python37/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/user/miniconda3/envs/python37/lib/python3.7/site-packages/torch/include -I/home/user/miniconda3/envs/python37/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/home/user/miniconda3/envs/python37/lib/python3.7/site-packages/torch/include/TH -I/home/user/miniconda3/envs/python37/lib/python3.7/site-packages/torch/include/THC -I/usr/local/cuda-11.0/include -I/home/user/miniconda3/envs/python37/include/python3.7m -c -c /home/user/dev/NSVF/fairnr/clib/src/octree.cpp -o /home/user/dev/NSVF/build/temp.linux-x86_64-3.7/fairnr/clib/src/octree.o -O2 -Ifairnr/clib/include -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=_ext -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
    /home/user/dev/NSVF/fairnr/clib/src/octree.cpp:6:10: fatal error: octree.h: No such file or directory
        6 | #include "octree.h"
          |          ^~~~~~~~~~
    compilation terminated.
    [3/6] c++ -MMD -MF /home/user/dev/NSVF/build/temp.linux-x86_64-3.7/fairnr/clib/src/binding.o.d -pthread -B /home/user/miniconda3/envs/python37/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/user/miniconda3/envs/python37/lib/python3.7/site-packages/torch/include -I/home/user/miniconda3/envs/python37/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/home/user/miniconda3/envs/python37/lib/python3.7/site-packages/torch/include/TH -I/home/user/miniconda3/envs/python37/lib/python3.7/site-packages/torch/include/THC -I/usr/local/cuda-11.0/include -I/home/user/miniconda3/envs/python37/include/python3.7m -c -c /home/user/dev/NSVF/fairnr/clib/src/binding.cpp -o /home/user/dev/NSVF/build/temp.linux-x86_64-3.7/fairnr/clib/src/binding.o -O2 -Ifairnr/clib/include -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=_ext -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
    FAILED: /home/user/dev/NSVF/build/temp.linux-x86_64-3.7/fairnr/clib/src/binding.o
    c++ -MMD -MF /home/user/dev/NSVF/build/temp.linux-x86_64-3.7/fairnr/clib/src/binding.o.d -pthread -B /home/user/miniconda3/envs/python37/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/user/miniconda3/envs/python37/lib/python3.7/site-packages/torch/include -I/home/user/miniconda3/envs/python37/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/home/user/miniconda3/envs/python37/lib/python3.7/site-packages/torch/include/TH -I/home/user/miniconda3/envs/python37/lib/python3.7/site-packages/torch/include/THC -I/usr/local/cuda-11.0/include -I/home/user/miniconda3/envs/python37/include/python3.7m -c -c /home/user/dev/NSVF/fairnr/clib/src/binding.cpp -o /home/user/dev/NSVF/build/temp.linux-x86_64-3.7/fairnr/clib/src/binding.o -O2 -Ifairnr/clib/include -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=_ext -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
    /home/user/dev/NSVF/fairnr/clib/src/binding.cpp:6:10: fatal error: intersect.h: No such file or directory
        6 | #include "intersect.h"
          |          ^~~~~~~~~~~~~
    compilation terminated.
    [4/6] c++ -MMD -MF /home/user/dev/NSVF/build/temp.linux-x86_64-3.7/fairnr/clib/src/sample.o.d -pthread -B /home/user/miniconda3/envs/python37/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/user/miniconda3/envs/python37/lib/python3.7/site-packages/torch/include -I/home/user/miniconda3/envs/python37/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/home/user/miniconda3/envs/python37/lib/python3.7/site-packages/torch/include/TH -I/home/user/miniconda3/envs/python37/lib/python3.7/site-packages/torch/include/THC -I/usr/local/cuda-11.0/include -I/home/user/miniconda3/envs/python37/include/python3.7m -c -c /home/user/dev/NSVF/fairnr/clib/src/sample.cpp -o /home/user/dev/NSVF/build/temp.linux-x86_64-3.7/fairnr/clib/src/sample.o -O2 -Ifairnr/clib/include -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=_ext -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
    FAILED: /home/user/dev/NSVF/build/temp.linux-x86_64-3.7/fairnr/clib/src/sample.o
    c++ -MMD -MF /home/user/dev/NSVF/build/temp.linux-x86_64-3.7/fairnr/clib/src/sample.o.d -pthread -B /home/user/miniconda3/envs/python37/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/user/miniconda3/envs/python37/lib/python3.7/site-packages/torch/include -I/home/user/miniconda3/envs/python37/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/home/user/miniconda3/envs/python37/lib/python3.7/site-packages/torch/include/TH -I/home/user/miniconda3/envs/python37/lib/python3.7/site-packages/torch/include/THC -I/usr/local/cuda-11.0/include -I/home/user/miniconda3/envs/python37/include/python3.7m -c -c /home/user/dev/NSVF/fairnr/clib/src/sample.cpp -o /home/user/dev/NSVF/build/temp.linux-x86_64-3.7/fairnr/clib/src/sample.o -O2 -Ifairnr/clib/include -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=_ext -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
    /home/user/dev/NSVF/fairnr/clib/src/sample.cpp:6:10: fatal error: sample.h: No such file or directory
        6 | #include "sample.h"
          |          ^~~~~~~~~~
    compilation terminated.
    [5/6] /usr/local/cuda-11.0/bin/nvcc --generate-dependencies-with-compile --dependency-output /home/user/dev/NSVF/build/temp.linux-x86_64-3.7/fairnr/clib/src/sample_gpu.o.d -I/home/user/miniconda3/envs/python37/lib/python3.7/site-packages/torch/include -I/home/user/miniconda3/envs/python37/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/home/user/miniconda3/envs/python37/lib/python3.7/site-packages/torch/include/TH -I/home/user/miniconda3/envs/python37/lib/python3.7/site-packages/torch/include/THC -I/usr/local/cuda-11.0/include -I/home/user/miniconda3/envs/python37/include/python3.7m -c -c /home/user/dev/NSVF/fairnr/clib/src/sample_gpu.cu -o /home/user/dev/NSVF/build/temp.linux-x86_64-3.7/fairnr/clib/src/sample_gpu.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -O2 -Ifairnr/clib/include -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=_ext -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_70,code=compute_70 -gencode=arch=compute_70,code=sm_70 -std=c++14
    FAILED: /home/user/dev/NSVF/build/temp.linux-x86_64-3.7/fairnr/clib/src/sample_gpu.o
    /usr/local/cuda-11.0/bin/nvcc --generate-dependencies-with-compile --dependency-output /home/user/dev/NSVF/build/temp.linux-x86_64-3.7/fairnr/clib/src/sample_gpu.o.d -I/home/user/miniconda3/envs/python37/lib/python3.7/site-packages/torch/include -I/home/user/miniconda3/envs/python37/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/home/user/miniconda3/envs/python37/lib/python3.7/site-packages/torch/include/TH -I/home/user/miniconda3/envs/python37/lib/python3.7/site-packages/torch/include/THC -I/usr/local/cuda-11.0/include -I/home/user/miniconda3/envs/python37/include/python3.7m -c -c /home/user/dev/NSVF/fairnr/clib/src/sample_gpu.cu -o /home/user/dev/NSVF/build/temp.linux-x86_64-3.7/fairnr/clib/src/sample_gpu.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -O2 -Ifairnr/clib/include -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=_ext -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_70,code=compute_70 -gencode=arch=compute_70,code=sm_70 -std=c++14
    /home/user/dev/NSVF/fairnr/clib/src/sample_gpu.cu:11:10: fatal error: cuda_utils.h: No such file or directory
       11 | #include "cuda_utils.h"
          |          ^~~~~~~~~~~~~~
    compilation terminated.
    [6/6] /usr/local/cuda-11.0/bin/nvcc --generate-dependencies-with-compile --dependency-output /home/user/dev/NSVF/build/temp.linux-x86_64-3.7/fairnr/clib/src/intersect_gpu.o.d -I/home/user/miniconda3/envs/python37/lib/python3.7/site-packages/torch/include -I/home/user/miniconda3/envs/python37/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/home/user/miniconda3/envs/python37/lib/python3.7/site-packages/torch/include/TH -I/home/user/miniconda3/envs/python37/lib/python3.7/site-packages/torch/include/THC -I/usr/local/cuda-11.0/include -I/home/user/miniconda3/envs/python37/include/python3.7m -c -c /home/user/dev/NSVF/fairnr/clib/src/intersect_gpu.cu -o /home/user/dev/NSVF/build/temp.linux-x86_64-3.7/fairnr/clib/src/intersect_gpu.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -O2 -Ifairnr/clib/include -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=_ext -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_70,code=compute_70 -gencode=arch=compute_70,code=sm_70 -std=c++14
    FAILED: /home/user/dev/NSVF/build/temp.linux-x86_64-3.7/fairnr/clib/src/intersect_gpu.o
    /usr/local/cuda-11.0/bin/nvcc --generate-dependencies-with-compile --dependency-output /home/user/dev/NSVF/build/temp.linux-x86_64-3.7/fairnr/clib/src/intersect_gpu.o.d -I/home/user/miniconda3/envs/python37/lib/python3.7/site-packages/torch/include -I/home/user/miniconda3/envs/python37/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/home/user/miniconda3/envs/python37/lib/python3.7/site-packages/torch/include/TH -I/home/user/miniconda3/envs/python37/lib/python3.7/site-packages/torch/include/THC -I/usr/local/cuda-11.0/include -I/home/user/miniconda3/envs/python37/include/python3.7m -c -c /home/user/dev/NSVF/fairnr/clib/src/intersect_gpu.cu -o /home/user/dev/NSVF/build/temp.linux-x86_64-3.7/fairnr/clib/src/intersect_gpu.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -O2 -Ifairnr/clib/include -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=_ext -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_70,code=compute_70 -gencode=arch=compute_70,code=sm_70 -std=c++14
    /home/user/dev/NSVF/fairnr/clib/src/intersect_gpu.cu:11:10: fatal error: cuda_utils.h: No such file or directory
       11 | #include "cuda_utils.h"
          |          ^~~~~~~~~~~~~~
    compilation terminated.
    ninja: build stopped: subcommand failed.
    Traceback (most recent call last):
      File "/home/user/miniconda3/envs/python37/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1673, in _run_ninja_build
        env=env)
      File "/home/user/miniconda3/envs/python37/lib/python3.7/subprocess.py", line 512, in run
        output=stdout, stderr=stderr)
    subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.
    
    The above exception was the direct cause of the following exception:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/user/dev/NSVF/setup.py", line 35, in <module>
        'fairnr-train = fairseq_cli.train:cli_main'
      File "/home/user/miniconda3/envs/python37/lib/python3.7/site-packages/setuptools/__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "/home/user/miniconda3/envs/python37/lib/python3.7/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/home/user/miniconda3/envs/python37/lib/python3.7/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/home/user/miniconda3/envs/python37/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/home/user/miniconda3/envs/python37/lib/python3.7/site-packages/setuptools/command/develop.py", line 34, in run
        self.install_for_development()
      File "/home/user/miniconda3/envs/python37/lib/python3.7/site-packages/setuptools/command/develop.py", line 136, in install_for_development
        self.run_command('build_ext')
      File "/home/user/miniconda3/envs/python37/lib/python3.7/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/home/user/miniconda3/envs/python37/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/home/user/miniconda3/envs/python37/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 79, in run
        _build_ext.run(self)
      File "/home/user/miniconda3/envs/python37/lib/python3.7/site-packages/Cython/Distutils/old_build_ext.py", line 186, in run
        _build_ext.build_ext.run(self)
      File "/home/user/miniconda3/envs/python37/lib/python3.7/distutils/command/build_ext.py", line 340, in run
        self.build_extensions()
      File "/home/user/miniconda3/envs/python37/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 708, in build_extensions
        build_ext.build_extensions(self)
      File "/home/user/miniconda3/envs/python37/lib/python3.7/site-packages/Cython/Distutils/old_build_ext.py", line 195, in build_extensions
        _build_ext.build_ext.build_extensions(self)
      File "/home/user/miniconda3/envs/python37/lib/python3.7/distutils/command/build_ext.py", line 449, in build_extensions
        self._build_extensions_serial()
      File "/home/user/miniconda3/envs/python37/lib/python3.7/distutils/command/build_ext.py", line 474, in _build_extensions_serial
        self.build_extension(ext)
      File "/home/user/miniconda3/envs/python37/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 196, in build_extension
        _build_ext.build_extension(self, ext)
      File "/home/user/miniconda3/envs/python37/lib/python3.7/distutils/command/build_ext.py", line 534, in build_extension
        depends=ext.depends)
      File "/home/user/miniconda3/envs/python37/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 538, in unix_wrap_ninja_compile
        with_cuda=with_cuda)
      File "/home/user/miniconda3/envs/python37/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1359, in _write_ninja_file_and_compile_objects
        error_prefix='Error compiling objects for extension')
      File "/home/user/miniconda3/envs/python37/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1683, in _run_ninja_build
        raise RuntimeError(message) from e
    RuntimeError: Error compiling objects for extension
    ----------------------------------------
ERROR: Command errored out with exit status 1: /home/user/miniconda3/envs/python37/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/user/dev/NSVF/setup.py'"'"'; __file__='"'"'/home/user/dev/NSVF/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command output.
```

What is peculiar is that copy pasting individual build commands, such as the follow one, compile correctly on their own.
```
$ c++ -MMD -MF /home/user/dev/NSVF/build/temp.linux-x86_64-3.7/fairnr/clib/src/intersect.o.d -pthread -B /home/user/miniconda3/envs/python37/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/user/miniconda3/envs/python37/lib/python3.7/site-packages/torch/include -I/home/user/miniconda3/envs/python37/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/home/user/miniconda3/envs/python37/lib/python3.7/site-packages/torch/include/TH -I/home/user/miniconda3/envs/python37/lib/python3.7/site-packages/torch/include/THC -I/usr/local/cuda-11.0/include -I/home/user/miniconda3/envs/python37/include/python3.7m -c -c /home/user/dev/NSVF/fairnr/clib/src/intersect.cpp -o /home/user/dev/NSVF/build/temp.linux-x86_64-3.7/fairnr/clib/src/intersect.o -O2 -Ifairnr/clib/include -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=_ext -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
In file included from /home/user/miniconda3/envs/python37/lib/python3.7/site-packages/torch/include/ATen/Parallel.h:140,
[...]
                 from /home/user/dev/NSVF/fairnr/clib/src/intersect.cpp:6:
/home/user/miniconda3/envs/python37/lib/python3.7/site-packages/torch/include/ATen/ParallelOpenMP.h:83: warning: ignoring #pragma omp parallel [-Wunknown-pragmas]
   83 | #pragma omp parallel for if ((end - begin) >= grain_size)
      | 
In file included from /home/user/miniconda3/envs/python37/lib/python3.7/site-packages/torch/include/c10/core/DeviceType.h:8,
[...]
                 from /home/user/dev/NSVF/fairnr/clib/src/intersect.cpp:6:
/home/user/dev/NSVF/fairnr/clib/src/intersect.cpp: In function ‘std::tuple<at::Tensor, at::Tensor, at::Tensor> ball_intersect(at::Tensor, at::Tensor, at::Tensor, float, int)’:
fairnr/clib/include/utils.h:12:24: warning: ‘at::DeprecatedTypeProperties& at::Tensor::type() const’ is deprecated: Tensor.type() is deprecated. Instead use Tensor.options(), which in many cases (e.g. in a constructor) is a drop-in replacement. If you were using data from type(), that is now available from Tensor itself, so instead of tensor.type().scalar_type(), use tensor.scalar_type() instead and instead of tensor.type().backend() use tensor.device(). [-Wdeprecated-declarations]
   12 |     TORCH_CHECK(x.type().is_cuda(), #x " must be a CUDA tensor"); \
[...]
```
The individual build command finishes with warnings but without errors.

**To Reproduce**
Following the README, at the installation step, running either `pip install --editable ./` or `python setup.py build_ext --inplace` results in the build failures detailed above. 

**Expected behavior**
Build should pass.

**Desktop (please complete the following information):**
 Ubuntu 18, CUDA 11.3, g++ version 9.3.0.

**Comment by nvibd** [comment]
Update: Also tested with g++ 7.5.0, different pytorch versions (as recommended here: https://github.com/facebookresearch/NSVF/issues/45), as well as various system CUDA versions (11.0, 11.2). The error stays the same.

**Comment by morsingher** [comment]
Same here. Did someone manage to fix this?

**Comment by ventusff** [comment]
Hi all,

It's because `CUDAExtension(extra_compile_args=...)` in `setup.py` is not accepting relative paths correctly.

- solution: 
change this line https://github.com/facebookresearch/NSVF/blob/12e63e71243a3fd0f90a953626b0c98c95687aa0/setup.py#L11
into
```python
import os
_ext_src_root = os.path.join(os.path.dirname(os.path.abspath(__file__)), "fairnr/clib")
```

Then your day is saved.
